### PR TITLE
[Releases] Reduced dataset for DBSCAN batch example

### PR DESCRIPTION
**Pull request by vepifanov**
Reduced dataset for DBSCAN batch example

### CODE REVIEW

**Comment by napetrov** [comment]
make test

**Comment by napetrov** [comment]
restarted testing - http://intel-ci.intel.com/ea393199-5fe2-f15f-b2f2-8cdcd4b723a1

**Comment by vepifanov** [comment]
Pulled latest changes from releases branch, restarted testing - http://intel-ci.intel.com/ea393cfe-91a4-f1d0-8db5-8cdcd4b723a1

**Comment by vepifanov** [comment]
Testing for lnx/mac - http://intel-ci.intel.com/ea393fb0-2615-f11b-a2bd-8cdcd4b723a1

**Pull request merged**
