### PR TITLE
Fix build for VS in mnt

### PR DESCRIPTION
**Pull request by dmitry741**
Fix problems with build for VS

### CODE REVIEW

**Comment by dmitry741** [comment]
make test

**Comment by prutskov** [comment]
@dmitry741 can you run VS check and add link to it?

**Comment by dmitry741** [comment]
link to CI: http://intel-ci.intel.com/ea5245a8-0321-f1be-a9f3-8cdcd4b723a1

**Comment by dmitry741** [comment]
new link to Weekly scope: https://ecmd.inn.intel.com/commander/link/jobDetails/jobs/ea52f7d7-dff6-f14d-82f7-8cdcd4b723a1

**Comment by dmitry741** [comment]
new link: https://ecmd.inn.intel.com/commander/link/jobDetails/jobs/ea5335d2-4f84-f1c1-ae09-8cdcd4b723a1

**Pull request merged**
