### PR TITLE
Refine usage of daal namespaces in examples

### PR DESCRIPTION
**Pull request by averbukh**
(cherry picked from commit 0d99c21317689b0e1a8b330366f5f9b2a8ec4aad)

# Description
Fix for incorrect 'using namespace' usage in the examples

### CODE REVIEW

**Comment by averbukh** [comment]
make test

**Comment by napetrov** [comment]
Looks there is lot of failures related to examples in CI - don't think they are expected

**Comment by averbukh** [comment]
> Looks there is lot of failures related to examples in CI - don't think they are expected

It's because you didn't squash it for merge into master, and I cherry picked one commit only.

**Comment by averbukh** [comment]
make test

**Pull request merged**
