### PR TITLE
Replace relative includes with full paths (#346)

### PR DESCRIPTION
**Pull request by rlnx**
see #346
- Replaced all chaotic includes in all .cpp/.h/.i files with the includes relative to <root>
and<root>/include directories
- Updated Makefile by removing `-I` flags to include paths

### CODE REVIEW

**Comment by napetrov** [comment]
make test

**Comment by napetrov** [comment]
I see noticeable build speedup with this change. :fire:

**Comment by rlnx** [comment]
make test

**Comment by napetrov** [comment]
restart

**Comment by rlnx** [comment]
This is valid one http://intel-ci.intel.com/ea4988fe-88cf-f168-9c22-8cdcd4b723a1

**Comment by rlnx** [comment]
> I see noticeable build speedup with this change. 🔥

@napetrov, I also noticed we compile twice the same files with the same options -- one for static, another for dynamic lib. On Linux and Mac it is not necessary, make sense only on Windows. Probably, we can speedup build 2x on Linux and Mac for free.

**Comment by napetrov** [comment]
@rlnx  yes, i've also check that we do strange things like building knl optimizations on mac using AVX2 target.   But for sure changing logic for staic->dynamic build will help.

**Pull request merged**
