### PR TITLE
move doxygen files to subfolder (#439)

### LINKED ISSUE #180: Moving Doxygen-files in sub directory
Here are too many files for Doxygen in the root directory, it is not frequently used functionality and it complicates access to other important files in root-folder like makefiles:
image

My proposal is moving them in some sub-folder and check that all QA infrastructure works correctly.

### PR DESCRIPTION
**Pull request by napetrov**
In this change we are moving doxygen files to sub-folder in order to fix issue #180 
Fixes #180

### CODE REVIEW

**Comment by napetrov** [comment]
make test
set infra_branch=cherry-pick-f5c32c1c

**Comment by dr-pain** [comment]
Why you didn`t move custom folder to the docs? How many documentation folder we want to have in the root?

**Comment by napetrov** [comment]
> 
> 
> here is quotation from #180:
> for master and releases branches: move doxygen configs and custom folder into docs/doxygen folder

Fixed, please check

**Comment by napetrov** [comment]
make test set infra_branch=cherry-pick-f5c32c1c

**Pull request merged**
