### PR TITLE
Fix exports in functions of data conversion

### PR DESCRIPTION
**Pull request by prutskov**

### CODE REVIEW

**Comment by prutskov** [comment]
make test

**Comment by ShvetsKS** [comment]
could you check Visual Studio build and reduced testing additionally to make sure that problem was fixed?

**Comment by prutskov** [comment]
PCm VS: http://intel-ci.intel.com/ea521cce-17f6-f109-8d1c-8cdcd4b723a1

**Comment by prutskov** [comment]
make test

**Pull request closed without merging**
